### ISSUE TITLE
provide thumbnail in response

### ISSUE THREAD

**Issue by itsjwala** [dvishal485/flipkart-scraper-api#1]
Hello Vishal, thanks a lot for this library 

for my use case I see one thing missing which is having a thumbnail in response, would it be possible to add it?
I know the code is closed source, I would've contributed and not bother with this feature request. 

Thanks

**Comment by dvishal485** [comment]
**Feature Added! 😃**

I will like to inform you that I have **added thumbnails support** as well in the API. Documentation will soon be added, but it's pretty obvious to assume you will get to know it's usage upon using the API. I apologize for the project to be closed source due to the messy code work!

_Thanks for you kind words! If you like my work, consider giving a star_ ⭐

**Comment by itsjwala** [comment]
Awesome, thanks for prompt response, sure you deserve it
