### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by himanshu8443** [dvishal485/flipkart-scraper-api#14]
{
    "error": "Internal Server Error. Host is down or is blocking use of this library."
}

**Comment by dvishal485** [comment]
Error message says it all. This error will only be raised if flipkart blocks the request thereby returning an "*Internal Server Error*" page. You may be trying to host this on a service which may be blacklisted by Flipkart. You can try hosting the service on your local device.

For any more information try to be elaborate with your working environment and/or the product url with which error may be reproduced.

**Comment by himanshu8443** [comment]
Currently running on AWS EC2 Mumbai region.
getting error in all products
I want to host it on cloud is there any solution?

**Comment by dvishal485** [comment]
Using VPN or Proxy may help. But I highly doubt this will help (being public IP themselves). It is not really something we have control over.

If architecture of your project allows, then you should make fetch calls on client side rather than on server.

Yet if you figure out a way to achieve hosting on public server, do give an update here.

**Comment by dvishal485** [comment]
I'm marking this issue as closed as the possible solution has been shared. And there is nothing else which can be done as per best of my knowledge.

**Comment by himanshu8443** [comment]
Update :  I couldn't find any Free solution but You can use residential proxies with IP rotation to bypass IP blocking 
                from Flipkart or any other site.
                I am using Bright Data web unblocker (https://brightdata.com/). It gives some free credits.
