### ISSUE TITLE
Are you human?

### ISSUE THREAD

**Issue by krishd9895** [dvishal485/flipkart-scraper-api#25]
{'name': 'Are you a human?', 'current_price': None, 'original_price': None, 'discounted': False, 'discount_percent': None, 'rating': None, 'in_stock': True, 'f_assured': False, 'share_url': 'https://www.flipkart.com/hp-intel-core-n-n200-8-gb-128-gb-chrome-os-14b-cd0012tu-chromebook/p/itm2febe6de6c14f?lid=LSTCOMH2V5YTQTHVZGNLPTUWM&marketplace=FLIPKART&hl_lid=&pid=COMH2V5YTQTHVZGN&store=6bo%2Fb5g&pageUID=1722778881064', 'seller': None, 'thumbnails': [], 'highlights': [], 'product_id': None, 'offers': [], 'specs': []}

**Comment by dvishal485** [comment]
Cannot reproduce on localhost. Are you using a deployed version of server?

**Comment by krishd9895** [comment]
I deployed it on render

**Comment by dvishal485** [comment]
On a remote server, like that of render, the API's network response is sent by Flipkart with intent to block web scraping. Hence the page results to "Are you a human?".
That being said, it is expected behavior to have such response, but should throw an error instead of title being coded to this "Are you human?". Expect it to be patched (throw instead of weird product name) in the next version.

**Comment by dvishal485** [comment]
Cannot replicate even on server.

Throws error as expected in my case, can you send log of the page contents?

If you don't know Rust, then just send the response of flipkart product page, simply using curl command as follows and attach the `response.txt`.

```bash
curl "https://www.flipkart.com/hp-intel-core-n-n200-8-gb-128-gb-chrome-os-14b-cd0012tu-chromebook/p/itm2febe6de6c14f?lid=LSTCOMH2V5YTQTHVZGNLPTUWM&marketplace=FLIPKART&hl_lid=&pid=COMH2V5YTQTHVZGN&store=6bo%2Fb5g&pageUID=1722778881064" > response.txt
```
